### ISSUE TITLE
Tareas semanales que no son de Servisofts

### ISSUE THREAD

**Issue by rickypazd** [CalisteniaBolivia-SRL/.github#10]
Se solicita a Alvaro que cree un reporte de las tareas que desempeña semanalmente que no son relacionadas con el desarrollo del sistema  `Servisofts`.

**Comment by alvarosiles11** [comment]
Archivo excel
[Funciones Alvaro.xlsx](https://github.com/CalisteniaBolivia-SRL/.github/files/15387126/Funciones.Alvaro.xlsx)

**Comment by alvarosiles11** [comment]
![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/01a7fce9-ae23-45bb-bf06-04fbf48ded17)

**Comment by alvarosiles11** [comment]
![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/bc7f0370-7a3b-4eef-a7b1-8d042f46b35e)
