### ISSUE TITLE
Informe de incidentes: caídas recurrentes del servidor de usuarios y calistenia semanal

### ISSUE THREAD

**Issue by alvarosiles11** [CalisteniaBolivia-SRL/.github#17]
Se registraron múltiples incidentes de caída del servidor de usuarios y calistenia semanal. A continuación se detallan los períodos afectados.

**Comment by alvarosiles11** [comment]
Se cayo Servidor Usuarios 20-05-2024, de 8:05 am a 8:29 am.
![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/0f356681-49fe-48c0-9dea-14b7ac4fb69f)

**Comment by alvarosiles11** [comment]
Se cayo Servidor Roles_Permisos  Y Usuarios 21-05-2024, de 6:25 am a 9:10 am.
![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/ab529235-bbbe-49cf-8849-862f7551c84d)
![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/6bc951c1-12c1-4c5f-98ec-a0df4b8b19d7)

**Comment by alvarosiles11** [comment]
Se cayo Servidor  Usuarios 22-05-2024, de 9:02 am
![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/753d0a6e-b5f7-4751-8526-393f03f813db)

**Comment by ruddypazd** [comment]
El día 23 no cayó en la mañana?

**Comment by alvarosiles11** [comment]
Se cayo Servidor Usuarios 23-05-2024, de 19:10 pm hasta las 20:00pm
![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/eb58f1c8-8cfa-4eb3-986f-6001d7f8245e)

![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/bf6a41bf-c26b-4283-9e49-0c5c42e77d0f)
@ruddypazd  @rickypazd
