### ISSUE TITLE
El servidor de banco_ganadero se cayó 27/05/24

### ISSUE THREAD

**Issue by alvarosiles11** [CalisteniaBolivia-SRL/.github#22]
El servidor de banco_ganadero está caído. Adjunto una captura de pantalla para referencia.

Problema:

No se pueden crear códigos QR en la aplicación.
No se pueden ver los pagos realizados mediante QR.
Pasos para reproducir el problema:

Intentar crear un código QR en la app.
Intentar visualizar pagos realizados mediante QR.
Captura de pantalla:
![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/fa00b18d-faf0-4c2b-a835-0e573d5cfc09)

**Comment by ruddypazd** [comment]
![IMG-20240527-WA0024.jpg](https://github.com/CalisteniaBolivia-SRL/.github/assets/7370358/bb17b3d9-e5b0-4fef-8710-c4e95355cb60)

Acabo de revisar y está todo correcto

**Comment by alvarosiles11** [comment]
![c70bcad2-ac5e-4c6f-9507-a5073bd54b32](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/68def29e-7f9e-427f-b050-778a469e9956)

**Comment by alvarosiles11** [comment]
pero ya se solucionó
