### ISSUE TITLE
Implementar proceso manual de facturación para ventas en el sistema

### ISSUE THREAD

**Issue by alvarosiles11** [CalisteniaBolivia-SRL/.github#4]
> Necesitamos desactivar la facturación automática de ventas en la aplicación móvil de calistenia y establecer un proceso manual. Al final de cada día, un responsable debe revisar y enviar las facturas a impuestos (SIAT). Las facturas deben cambiarse de "emitida" a "enviado" una vez que se haya completado el proceso manual.
> 
> * [ ]  mejora
> * [ ]  facturación
> * [ ]  proceso manual
> 
> @ruddypazd @rickypazd

![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/cf6b456b-a17d-4855-a557-e27753f7075b)

**Comment by rickypazd** [comment]
Primero hay que desactivar la facturacion automartica desde el servidor.

Desde la ventana de ventas ya tiene el boton emitir factura entonces solo eso seria el trabajo.

**Comment by alvarosiles11** [comment]
1. Para desactivar la facturación automática en caja, modifica la línea 412 de la clase PaqueteVenta en el backend. 
2. Para desactivar la facturación automática en la aplicación, edita la línea 462 de la clase PaqueteVentaUsuario en el backend.

**Comment by alvarosiles11** [comment]
Se va a modificar/actualizar el reporte
pagina PaquetesVendidos

![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/97375d7f-7892-466a-b96f-f814ab73cd63)

**Comment by alvarosiles11** [comment]
Se ha incorporado una columna de estado en color, que indica si está pendiente o en proceso de envío, y el botón de facturación se activa cuando el estado es pendiente o no se ha asignado un código de factura

![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/e7baff81-0cd0-4536-81d5-d634cc97a3af)
