### ISSUE TITLE
SERVIDOR: USUARIOS Solucionar bug que impide la actualización correcta al eliminar la huella digital de un usuario.

### ISSUE THREAD

**Issue by alvarosiles11** [CalisteniaBolivia-SRL/.github#58]

**Comment by rickypazd** [comment]
Se necesita un trabajo en conjunto con ATC de una sucursal para reportar al momento que un cliente renueva un paquete para que veamos por que.

**Comment by alvarosiles11** [comment]
Se realizaron pruebas de los casos del molinete Suc. Cusis.
El día 4/12/2024, se visitó la sucursal correspondiente, trabajando en conjunto con Ricardo para resolver los puntos pendientes del molinete.
