### ISSUE TITLE
Confirmación al anular una factura, pagina "Paquetes vendidos"

### ISSUE THREAD

**Issue by alvarosiles11** [CalisteniaBolivia-SRL/.github#7]
Problema:
Al presionar el botón "Anular Factura", actualmente se anula la factura de forma inmediata. Esto puede llevar a errores si el encargado de anular la factura lo hace por accidente.

Solución Propuesta:
Implementar un mensaje de confirmación que aparezca al presionar el botón "Anular Factura". Este mensaje debería preguntar al usuario si está seguro de que desea anular la factura, con opciones para confirmar o cancelar la acción.

Beneficios:

- Previene anulaciones accidentales.
- Asegura que solo se anulen facturas cuando el usuario está seguro de su decisión.
- Mejora la experiencia del usuario y reduce posibles errores administrativos.

Pasos para Reproducir:

1. Navegar a la sección de facturas.
2. Seleccionar una factura.
3. Presionar el botón "Anular Factura".

Resultado Esperado:
Aparece un mensaje de confirmación que solicita la confirmación del usuario antes de anular la factura.

Notas Adicionales:
Adjuntar cualquier captura de pantalla o detalles adicionales que puedan ayudar a ilustrar el problema y la solución.

![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/091e3d34-59e1-4f03-96f7-fa0592e86494)

**Comment by ruddypazd** [comment]
@alvarosiles11 no es necesario etiquetarnos porque ese issue, solo es en el panel administrativo y de front-end. 

Eso lo tendrías que hacer vos. 

Asignanos solo los que nos necesites.

**Comment by alvarosiles11** [comment]
solucionado
![image](https://github.com/CalisteniaBolivia-SRL/.github/assets/61075383/76c3c89e-e3dd-4f35-861f-449cd729cefc)
